projeto_prod:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_DEV_PROJECT') }}"
      dataset: "{{ env_var('DBT_DEV_SCHEMA') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_DEV_KEYFILE_PATH') }}"
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROD_PROJECT') }}"
      dataset: "{{ env_var('DBT_PROD_SCHEMA') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_PROD_KEYFILE_PATH') }}"